nelmio_api_doc:
  documentation:
    info:
      title: Local Brand Task
      description: Employee Mangament System
      version: 0.0.1
  areas:
    path_patterns: # an array of regexps
      - ^/api(?!/doc$)
#    host_patterns:
#      - ^api\.
