app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

show_employee:
  path: /api/employees/{id}
  methods: GET
  controller: App\Controller\ShowEmployeeAction

list_employees:
  path: /api/employees
  methods: GET
  controller: App\Controller\ListEmployeesAction

show_upload_employees:
  path: /employee/upload
  methods: GET
  controller:  App\Controller\ShowUploadEmployeesForm


upload_employees:
  path: /employee/upload
  methods: POST
  controller:  App\Controller\UploadEmployeesAction
