app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

show_employee:
  path: /api/employees/{id}
  methods: GET
  controller: App\Controller\ShowEmployeeAction
